// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatorPreview: typeof import('./src/components/worldeditor/AnimatorPreview.vue')['default']
    copy: typeof import('./src/components/worldeditor/entity/components/EntityComponentsTree copy.vue')['default']
    EntityComponentsTree: typeof import('./src/components/worldeditor/entity/components/EntityComponentsTree.vue')['default']
    EntityCreate: typeof import('./src/components/worldeditor/entity/EntityCreate.vue')['default']
    EntityEditor: typeof import('./src/components/worldeditor/entity/EntityEditor.vue')['default']
    EntityPropertiesTable: typeof import('./src/components/worldeditor/entity/properties/EntityPropertiesTable.vue')['default']
    EntityPropertiesTree: typeof import('./src/components/worldeditor/objects/properties/EntityPropertiesTree.vue')['default']
    EntityPropertyEditor: typeof import('./src/components/worldeditor/objects/properties/EntityPropertyEditor.vue')['default']
    EntityTree: typeof import('./src/components/worldeditor/entity/EntityTree.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTree: typeof import('naive-ui')['NTree']
    ObjectCreate: typeof import('./src/components/worldeditor/objects/ObjectCreate.vue')['default']
    ObjectPropertiesTree: typeof import('./src/components/worldeditor/objects/properties/ObjectPropertiesTree.vue')['default']
    ObjectPropertyEditor: typeof import('./src/components/worldeditor/objects/properties/ObjectPropertyEditor.vue')['default']
    ObjectsEditor: typeof import('./src/components/worldeditor/objects/ObjectsEditor.vue')['default']
    ObjectsTree: typeof import('./src/components/worldeditor/objects/ObjectsTree.vue')['default']
    ObjectTree: typeof import('./src/components/worldeditor/objects/ObjectTree.vue')['default']
    PixiApplication: typeof import('./src/components/pixi/app/PixiApplication.vue')['default']
    PixiAssets: typeof import('./src/components/pixi/assets/PixiAssets.vue')['default']
    PixiLoader: typeof import('./src/components/pixi/loader/PixiLoader.vue')['default']
    PixiTicker: typeof import('./src/components/pixi/ticker/PixiTicker.vue')['default']
    PixiViewport: typeof import('./src/components/pixi/viewport/PixiViewport.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeDeleteButton: typeof import('./src/components/worldeditor/objects/TreeDeleteButton.vue')['default']
  }
}
