// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatorPreview: typeof import('./src/components/worldeditor/AnimatorPreview.vue')['default'];
    PixiApplication: typeof import('./src/components/pixi/PixiApplication.vue')['default'];
    PixiLoader: typeof import('./src/components/pixi/PixiLoader.vue')['default'];
    PixiTicker: typeof import('./src/components/pixi/PixiTicker.vue')['default'];
    PixiViewport: typeof import('./src/components/pixi/PixiViewport.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
