name: PR

on:
  pull_request:
    branches:
      - main

env:
  CI: true

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install
        run: npm ci

      - name: lint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: junit.xml
          reporter: jest-junit

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true
